services:
  backend:
    build: ./flask
    container_name: gateway_backend
    ports:
      - "8080:8080"
    volumes:
      - ./flask:/app

  frontend:
    build: ./frontend
    container_name: gateway_frontend
    ports:
      - "5550:5550"
    depends_on:
      - backend